---
on:
  release:
    types:
      - created

permissions:
  contents: write
  packages: write

jobs:
  publish-binaries:
    name: publish binaries
    strategy:
      fail-fast: false
      matrix:
        goversion:
          - "1.22"
        goarch:
          - "386"
          - amd64
          - arm64
        goos:
          - darwin
          - linux
          - windows
        program:
          - gnokey
          - gnoland
          - gnoweb
        exclude:
          -
            goarch: "386"
            goos: darwin
          -
            goarch: arm64
            goos: windows
    runs-on: ubuntu-latest
    steps:
      -
        uses: actions/checkout@v4
      -
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.goversion }}.x
      -
        uses: wangyoucao577/go-release-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          goversion: ${{ matrix.goversion }}
          project_path: ./gno.land/cmd/${{ matrix.program }}
          binary_name: ${{ matrix.program }}
          md5sum: true
          sha256sum: true
